package com.nspl.agingoptions.financepage.testcases;

import java.time.Duration;
import java.util.Map;

import org.testng.annotations.Test;

import com.agingoptions.finance.Non_Retirement_And_RetirementPage;
import com.agingoptions.lpolandingpage.LpoLandingPage;
import com.aginoptions.legalpage.FiduciaryBeneficiaryPage;
import com.nspl.agingoptions.commoncode.AssetsCommonCode;
import com.nspl.agingoptions.commoncode.CommonCode;
import com.nspl.agingoptions.webUtil.BaseTest;
import com.nspl.agingoptions.webUtil.DataUtil;

public class RetirementTestCases extends BaseTest {

	@Test(priority = 1)
	public void FTC04_RetirementSaveContinueLaterButton() {

		LpoLandingPage lpo = new LpoLandingPage(util);
		CommonCode common = new CommonCode(util);
		lpo.clickLegalSideBarLink();
		lpo.clickFinanceSideBarLink();
		AssetsCommonCode assets = new AssetsCommonCode(util);
		assets.clickRetirementSideBarLink();
		assets.clickAddAssetButton();
		Non_Retirement_And_RetirementPage nonRetirement = new Non_Retirement_And_RetirementPage(util);
		nonRetirement.selectTraditionalIRAFromTypeOfRetirementDropDown();
		String expectedNameOfInstituion = "Indian Retirement Assets";
		nonRetirement.inputNameOfInstituion(expectedNameOfInstituion);
		String expectedBalance = "434534";
		nonRetirement.inputBalance(expectedBalance);
		nonRetirement.selectOwnerAsJoint();
		String expectedAccountNumber = "8743";
		nonRetirement.inputAccountNumber(expectedAccountNumber);
		nonRetirement.openAddressAccordian();
		// assets.inputAddress("122002");
		String expectedPhoneNumber = "8734563443";
		assets.inputPhoneNumber(expectedPhoneNumber);
		String expectedEmail = "rohannonretirementassets@maildrop.cc";
		assets.inputEmail(expectedEmail);
		nonRetirement.openBeneficiaryAccordian();
		nonRetirement.clickAddCharityButton();
		util.holdOn(Duration.ofSeconds(5));
		String expectedCharityName = "Sohan Charity";
		nonRetirement.inputCharityNameTB(expectedCharityName);
		String expectedPercetnage = "12";
		nonRetirement.inputPercentage(expectedPercetnage);
		// assets.inputAddress("122002");
		String expectedCharityPhoneNum = "7782734833";
		util.holdOn(Duration.ofSeconds(4));
		nonRetirement.inputCharityPhoneNumber(expectedCharityPhoneNum);
		String expectedCharityEmail = "sohancharity2983@maildrop.cc";
		util.holdOn(Duration.ofSeconds(1));
		nonRetirement.inputCharityEmail(expectedCharityEmail);
		util.holdOn(Duration.ofSeconds(1));
		nonRetirement.clickCharitySaveButton();
		util.holdOn(Duration.ofSeconds(1));
		nonRetirement.openDocumentUploadAccordian();
		assets.uploadFile();
		assets.clickSaveContinueLaterButton();
		assets.waitUntilNon_RetirementTableIsPresentInUI(40);
		nonRetirement.clickIndianNonRetirementEditIcon();
		util.holdOn(Duration.ofSeconds(5));
		String actualTypeOfAssetSelectOption = nonRetirement.getTypeOfAssetDropDownSelectedOption();
		String actualNameOfInstitutionValue = nonRetirement.getNameOfInstitutionInputValue();
		String actualBalance = nonRetirement.getBalanceInputValue();
		String actualOwnerSelectedText = nonRetirement.getOwnerSelectedText();
		String actualAccountNumberText = nonRetirement.getAccountNumberInputValue();
		nonRetirement.openAddressAccordian();
		String actualPhoneNo = assets.getPhoneNumberInputText();
		String acutalEmail = assets.getEmailInputText();
		nonRetirement.openBeneficiaryAccordian();
		nonRetirement.clickEditCharityButton();
		nonRetirement.waitUntilCharityModalIsOpen(10);
		util.holdOn(Duration.ofSeconds(3));
		String actualCharityName = nonRetirement.getCharityInputName();
		String actualCharityPercentage = nonRetirement.getCharityPercentageInputText();
		util.holdOn(Duration.ofSeconds(2));
		nonRetirement.waitUntilCharityModalIsOpen(5);
		String actualCharityInputPhoneNumber = nonRetirement.getCharityInputPhoneNumber();
		String acutalCharityEmail = nonRetirement.getCharityInputEmail();
		nonRetirement.clickCharityCancelButton();
		util.verifyActualExpectedText(actualTypeOfAssetSelectOption, "Traditional IRA", "Type of Retirement Asset*");
		util.verifyActualExpectedText(actualNameOfInstitutionValue, expectedNameOfInstituion, "Name of institution");
		util.verifyActualExpectedText(actualBalance, expectedBalance, "Balance");
		util.verifyActualExpectedText(actualOwnerSelectedText, "Joint", "Owner");
		util.verifyActualExpectedText(actualAccountNumberText, expectedAccountNumber, "Account Number");
		util.verifyActualExpectedText(actualPhoneNo, expectedPhoneNumber, "Phone Number");
		util.verifyActualExpectedText(acutalEmail, expectedEmail, "Email");
		util.verifyActualExpectedText(actualCharityName, expectedCharityName, "Charity Name");
		util.verifyActualExpectedText(actualCharityPercentage, expectedPercetnage, "Charity Percentage");
		util.verifyActualExpectedText(actualCharityInputPhoneNumber, expectedCharityPhoneNum, "Charity Phone Number");
		util.verifyActualExpectedText(expectedCharityEmail, acutalCharityEmail, "Charity Email");
		common.clickPreviousButton();

	}

	@Test(priority = 2)
	public void FTC05_RetirementSaveAddAnotherButton() {

		LpoLandingPage lpo = new LpoLandingPage(util);
		CommonCode common = new CommonCode(util);
		FiduciaryBeneficiaryPage fiduciary = new FiduciaryBeneficiaryPage(util);
		lpo.clickLegalSideBarLink();
		fiduciary.clickFiduciaryOrBeneficiaryLink();
		fiduciary.checkFiduciaryBeneficiaryCheckBox();
		fiduciary.clickProceedToSpouseButton();
		fiduciary.checkFiduciaryBeneficiaryCheckBox();
		fiduciary.clickProceedToLivingWillDetailsButton();
		util.refreshPage();
		lpo.clickFinanceSideBarLink();
		AssetsCommonCode assets = new AssetsCommonCode(util);
		assets.clickRetirementSideBarLink();
		assets.clickAddAssetButton();
		Non_Retirement_And_RetirementPage nonRetirement = new Non_Retirement_And_RetirementPage(util);
		nonRetirement.selectTraditionalIRAFromTypeOfRetirementDropDown();
		String expectedNameOfInstituion = "Bank of America";
		nonRetirement.inputNameOfInstituion(expectedNameOfInstituion);
		String expectedBalance = "984394";
		nonRetirement.inputBalance(expectedBalance);
		nonRetirement.selectPrimaryMemberAsOwner();
		String expectedAccountNumber = "8733";
		nonRetirement.inputAccountNumber(expectedAccountNumber);
		nonRetirement.openAddressAccordian();
		String expectedPhoneNumber = "8745874854";
		assets.inputPhoneNumber(expectedPhoneNumber);
		String expectedEmail = "skassetsofusa@maildrop.cc";
		assets.inputEmail(expectedEmail);
		nonRetirement.openBeneficiaryAccordian();
		nonRetirement.selectSpouseAsBeneficiary();
		String expectedPercentageValue = "4";
		nonRetirement.inputBeneficiaryPercentageText(expectedPercentageValue);
		util.holdOn(Duration.ofSeconds(1));
		nonRetirement.openDocumentUploadAccordian();
		assets.uploadFile();
		common.clickSaveAddAnotherButton();
		common.waitUntilToasterMessageisHide();
		assets.waitUntilPreviousButtonIsShown();
		common.clickPreviousButton();
		assets.waitUntilNon_RetirementTableIsPresentInUI(20);
		nonRetirement.clickBankOfAmericaEditIcon();
		util.holdOn(Duration.ofSeconds(3));
		String actualTypeOfAssetSelectOption = nonRetirement.getTypeOfAssetDropDownSelectedOption();
		String actualNameOfInstitutionValue = nonRetirement.getNameOfInstitutionInputValue();
		String actualBalance = nonRetirement.getBalanceInputValue();
		String actualOwnerSelectedText = nonRetirement.getOwnerSelectedText();
		String actualAccountNumberText = nonRetirement.getAccountNumberInputValue();
		nonRetirement.openAddressAccordian();
		String actualPhoneNo = assets.getPhoneNumberInputText();
		String acutalEmail = assets.getEmailInputText();
		nonRetirement.openBeneficiaryAccordian();
		String actualBeneficiary = nonRetirement.getBeneficiaryDropDownSelectedName();
		String actualPercentage = nonRetirement.getPercentageInputValue();
		DataUtil data = new DataUtil();
		Map<String, String> dataValue = data.getTestCaseData("Health_001");
		String firstName = dataValue.get("spouseFirstName");
		String lastName = dataValue.get("lastName");
		String primaryMemberFirstName=	dataValue.get("firstName");
		util.holdOn(Duration.ofSeconds(3));
		util.verifyActualExpectedText(actualTypeOfAssetSelectOption, "Traditional IRA", "Type Of Assets");
		util.verifyActualExpectedText(actualNameOfInstitutionValue, expectedNameOfInstituion, "Name of institution");
		util.verifyActualExpectedText(actualBalance, expectedBalance, "Balance");
		util.verifyActualExpectedText(actualOwnerSelectedText, primaryMemberFirstName+" "+lastName, "Owner");
		util.verifyActualExpectedText(actualAccountNumberText, expectedAccountNumber, "Account Number");
		util.verifyActualExpectedText(actualPhoneNo, expectedPhoneNumber, "Phone Number");
		util.verifyActualExpectedText(acutalEmail, expectedEmail, "Email");
		util.verifyActualExpectedTextContains(actualBeneficiary, firstName + " " + lastName, "Email");
		util.verifyActualExpectedText(actualPercentage, expectedPercentageValue, "Percentage");
		common.clickPreviousButton();
	}

	@Test(priority=3)
	public void FTC06_RetirementNextRealEstateButton() {

		LpoLandingPage lpo = new LpoLandingPage(util);
		CommonCode common = new CommonCode(util);
		FiduciaryBeneficiaryPage fiduciary = new FiduciaryBeneficiaryPage(util);
		lpo.clickLegalSideBarLink();
		fiduciary.clickFiduciaryOrBeneficiaryLink();
		fiduciary.checkFiduciaryBeneficiaryCheckBox();
		fiduciary.clickProceedToSpouseButton();
		fiduciary.checkFiduciaryBeneficiaryCheckBox();
		fiduciary.clickProceedToLivingWillDetailsButton();
		util.refreshPage();
		lpo.clickFinanceSideBarLink();
		AssetsCommonCode assets = new AssetsCommonCode(util);
		assets.clickRetirementSideBarLink();
		assets.clickAddAssetButton();
		Non_Retirement_And_RetirementPage nonRetirement = new Non_Retirement_And_RetirementPage(util);
		nonRetirement.selectOtherTypeOfAssets();
		String expectedNameOfInstituion = "Bank of United State Of America";
		nonRetirement.inputNameOfInstituion(expectedNameOfInstituion);
		String expectedOtherTextBoxValue="984 Plans";
		nonRetirement.inputOtherDescription(expectedOtherTextBoxValue);
		String expectedBalance = "984394";
		nonRetirement.inputBalance(expectedBalance);
		nonRetirement.selectPrimaryMemberAsOwner();
		String expectedAccountNumber = "8733";
		nonRetirement.inputAccountNumber(expectedAccountNumber);
		nonRetirement.openAddressAccordian();
		String expectedPhoneNumber = "8745874854";
		assets.inputPhoneNumber(expectedPhoneNumber);
		String expectedEmail = "skassetsofusa@maildrop.cc";
		assets.inputEmail(expectedEmail);
		nonRetirement.openBeneficiaryAccordian();
		nonRetirement.selectSpouseAsBeneficiary();
		String expectedPercentageValue = "4";
		nonRetirement.inputBeneficiaryPercentageText(expectedPercentageValue);
		util.holdOn(Duration.ofSeconds(1));
		nonRetirement.openDocumentUploadAccordian();
		assets.uploadFile();
		common.clickSaveAddAnotherButton();
		common.waitUntilToasterMessageisHide();
		assets.waitUntilPreviousButtonIsShown();
		common.clickPreviousButton();
		assets.waitUntilNon_RetirementTableIsPresentInUI(20);
		nonRetirement.clickBankOfUnitedStateOfAmericaEditIcon();
		util.holdOn(Duration.ofSeconds(3));
		String actualTypeOfAssetSelectOption = nonRetirement.getTypeOfAssetDropDownSelectedOption();
		String actualOtherDescriptionValue=	nonRetirement.getOtherDescriptionInputText();
		String actualNameOfInstitutionValue = nonRetirement.getNameOfInstitutionInputValue();
		String actualBalance = nonRetirement.getBalanceInputValue();
		String actualOwnerSelectedText = nonRetirement.getOwnerSelectedText();
		String actualAccountNumberText = nonRetirement.getAccountNumberInputValue();
		nonRetirement.openAddressAccordian();
		String actualPhoneNo = assets.getPhoneNumberInputText();
		String acutalEmail = assets.getEmailInputText();
		nonRetirement.openBeneficiaryAccordian();
		String actualBeneficiary = nonRetirement.getBeneficiaryDropDownSelectedName();
		String actualPercentage = nonRetirement.getPercentageInputValue();
		DataUtil data = new DataUtil();
		Map<String, String> dataValue = data.getTestCaseData("Health_001");
		String firstName = dataValue.get("spouseFirstName");
		String lastName = dataValue.get("lastName");
		String primaryMemberFirstName=	dataValue.get("firstName");
		util.holdOn(Duration.ofSeconds(3));
		util.verifyActualExpectedText(actualTypeOfAssetSelectOption, "Other", "Type Of Assets");
		util.verifyActualExpectedText(actualOtherDescriptionValue, expectedOtherTextBoxValue, "Other Text Box Value");
		util.verifyActualExpectedText(actualNameOfInstitutionValue, expectedNameOfInstituion, "Name of institution");
		util.verifyActualExpectedText(actualBalance, expectedBalance, "Balance");
		util.verifyActualExpectedText(actualOwnerSelectedText, primaryMemberFirstName+" "+lastName, "Owner");
		util.verifyActualExpectedText(actualAccountNumberText, expectedAccountNumber, "Account Number");
		util.verifyActualExpectedText(actualPhoneNo, expectedPhoneNumber, "Phone Number");
		util.verifyActualExpectedText(acutalEmail, expectedEmail, "Email");
		util.verifyActualExpectedTextContains(actualBeneficiary, firstName + " " + lastName, "Email");
		util.verifyActualExpectedText(actualPercentage, expectedPercentageValue, "Percentage");
		common.clickPreviousButton();
	}


}
