package com.agingoptions.myServiceProviderPage;

import static org.testng.Assert.fail;

import java.time.Duration;

import org.testng.Assert;

import com.nspl.agingoptions.webUtil.WebUtil;

public class MyServiceProviderPage extends MyServiceProviderPageOr {

	public WebUtil wt;

	public MyServiceProviderPage(WebUtil util) {
		super(util);
		this.wt=util;
	}

	public void verifyMyServiceproviderPage() {
		wt.verifyInnerText(MyServiceProviderText, "My service provider","My service provider page");
		;
	}
	public String verifyAddedprofessionalCountInTable() {
		String text=wt.getInnerText(ProfessionalCount);
		return text;
	}

	public void AddPhysician() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(PhysicianCheckBoxUnderDropdown, "Physician check box");
		wt.click(PhysicianCheckBoxUnderDropdown, "Physician check box");
		wt.holdOn(Duration.ofSeconds(3));
		wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(8));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="General Practitioner (GP)";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");


	}
	public void verifyClient() {
		wt.waitUntilPresentInUI(highlightedtoggleButton, "Highlighted toggle button");
		String text =wt.getInnerText(highlightedtoggleButton);
		wt.printDataInReport("we are going to fill detail for " + text);
	}
	public void verifyCopySameDataCheckBox() {
		wt.isSelected(CopySameDataToSpouseCheckBox, "Copy same data to spouse check box");
	}

	public void verifyAddHousingProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(HousingSpecialityDrawer, "Housing speciality ");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(AdultDayService, "Adult day service");
		wt.click(AdultDayService, "Adult day service");
		wt.holdOn(Duration.ofSeconds(3));
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(8));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Adult Day Service";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
	}

	public void verifyAddFinanceProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(FinancialSpecialityDrawer, "finance speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(CareManagement, "Care management");
		wt.click(CareManagement, "Care management");
		wt.holdOn(Duration.ofSeconds(3));
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(8));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Care Management";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
	}

	public void AddLegalProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(LegalSpecialityDrawer, "Legal speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(Other, "Other");
		wt.click(Other, "Other");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(OtherOptionDescription, "Legal's other", "Other description");
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(8));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Legal's other";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");
	}

	public void addSpecialist() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		//wt.click(HealthSpecialityDrawer, "Health speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(SpecialistCheckBoxUnderDropdown, "Specialist check box");
		wt.click(SpecialistCheckBoxUnderDropdown, "Specialist check box");
		wt.holdOn(Duration.ofSeconds(3));
		wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		wt.click(AccupressureUnderSubServiceProvider, "Accupressure check box");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "TEST", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(12));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalName=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalName,Name.toUpperCase() +" TEST", "Professional name");
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalNameforspouse=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalNameforspouse,Name.toUpperCase() +" TEST", "Professional name");
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.click(HealthSectionUnderSetupPage, "Health section under setup page");
		wt.click(HealthprofessionalDrawer, "health professional drawer");
		wt.click(specialistDrawer, "Specialist drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name +" Test", "Search bar");
		String professionalNameInHealthTable= wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains(professionalNameInHealthTable, Name.toUpperCase()+" TEST", "professional name");
		wt.click(MyServiceProviderSectionUndersetUpPage, "My service provider drawer under setup page");

	}
	
	public void addRealtor() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(HousingSpecialityDrawer, "Housing speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(RealtorCheckBoxUnderDropdown, "Realtor check box");
		wt.click(RealtorCheckBoxUnderDropdown, "Realtor check box");
		wt.holdOn(Duration.ofSeconds(3));
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "TEST", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(12));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalName=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalName,Name.toUpperCase() +" TEST", "Professional name");
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalNameforspouse=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalNameforspouse,Name.toUpperCase() +" TEST", "Professional name");
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.click(HousingSectionUnderSetUpPage, "Housing section under setup page");
		wt.click(HousingProfessionalDrawer, "housing professional drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name +" Test", "Search bar");
		String professionalNameInHealthTable= wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains(professionalNameInHealthTable, Name.toUpperCase()+" TEST", "professional name");
		wt.click(MyServiceProviderSectionUndersetUpPage, "My service provider drawer under setup page");
	}
	
	public void AddFinancialAdvisor() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(FinancialSpecialityDrawer, "Finance speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(FinancialAdvisorServiceProvider, "Financial advisor check box");
		wt.click(FinancialAdvisorServiceProvider, "financial advisor check box");
		wt.holdOn(Duration.ofSeconds(3));
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "TEST", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(12));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalName=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalName,Name.toUpperCase() +" TEST", "Professional name");
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalNameforspouse=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalNameforspouse,Name.toUpperCase() +" TEST", "Professional name");
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.click(FinanceProfessionalSectionUnderSetupPage, "Finance section under setup page");
		wt.click(FinanceProfessionalDrawer, "Finance professional drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name +" Test", "Search bar");
		String professionalNameInHealthTable= wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains(professionalNameInHealthTable, Name.toUpperCase()+" TEST", "professional name");
		wt.click(MyServiceProviderSectionUndersetUpPage, "My service provider drawer under setup page");	
	}
	
	public void AddELA() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(LegalSpecialityDrawer, "Legal speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(ELAdrawer, "ELA check box");
		wt.click(ELAdrawer, "ELA check box");
		wt.holdOn(Duration.ofSeconds(3));
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "TEST", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(12));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalName=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalName,Name.toUpperCase() +" TEST", "Professional name");
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String AddedProfessionalNameforspouse=  wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains( AddedProfessionalNameforspouse,Name.toUpperCase() +" TEST", "Professional name");
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.click(LegalButtonUnderSetUpPage, "Legal section under setup page");
		wt.click(LegalProfessionalDrawer, "Legal professional drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name +" Test", "Search bar");
		String professionalNameInHealthTable= wt.getInnerText(professonalNameInTable).toUpperCase();
		wt.verifyActualExpectedTextContains(professionalNameInHealthTable, Name.toUpperCase()+" TEST", "professional name");
		wt.click(MyServiceProviderSectionUndersetUpPage, "My service provider drawer under setup page");	
	}
	
	public void AddOtherTypeProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(OtherSpecialityDrawer, "Other speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(Other, "Other");
		wt.click(Other, "Other");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(OtherOptionDescription, "Other's other", "Other description");
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndContinueBT, "Save And Continue button");
		wt.holdOn(Duration.ofSeconds(8));
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Other's othe";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
	}
	
	public void saveAndProceedtoHomeProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(HousingSpecialityDrawer, "Housing speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(Other, "Other");
		wt.click(Other, "Other");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(OtherOptionDescription, "Other's other", "Other description");
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndProceedToHomeButton, "Save And proceed to Home button");
		wt.holdOn(Duration.ofSeconds(8));
		wt.verifyInnerText(PersonalInformationText, "Personal Information", "Personal information page");
		wt.click(MyServiceProviderSectionUndersetUpPage, "My service provider page");
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Other's other";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
	}
	
	public void VerifySaveAndAddAnotherProfessional() {
		String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(FinancialSpecialityDrawer, "Financial speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(Other, "Other");
		wt.click(Other, "Other");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(OtherOptionDescription, "Other's other", "Other description");
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "Test", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndAddAnotherBT, "Save and add another");
		wt.holdOn(Duration.ofSeconds(10));
		wt.click(PreviousIcon, "Previous Icon");
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse toggle button");
		wt.holdOn(Duration.ofSeconds(3));
		String  spouseRevisedProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
		wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Other's other";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
	}	
	
   public void SaveProfessionalDetailsWithCopySameDataToSpouseUnchecked() {
	   String primaryMemberInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(SpousetoggleButton, "Spouse tofggle button");
		wt.holdOn(Duration.ofSeconds(3));
		//String SpouseInitialProfessionalCount=wt.getInnerText(ProfessionalCount);
		wt.click(primaryMemberToggleButton, "Primary member toggle button");
		wt.holdOn(Duration.ofSeconds(2));
		verifyClient();
		wt.click(AddProfessionalButton, "Add professional button");	
		verifyCopySameDataCheckBox();
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(CopySameDataToSpouseCheckBox, "Copy same data to spouse Check box");
		wt.holdOn(Duration.ofSeconds(3));
		wt.click(FinancialSpecialityDrawer, "Financial speciality drawer");
		wt.holdOn(Duration.ofSeconds(5));
		wt.click(SelectServiceProviderDropdown, "Select service provider dropdown");
		wt.scrollIntoElement(Other, "Other");
		wt.click(Other, "Other");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(OtherOptionDescription, "Other's other", "Other description");
		//	   wt.click(SubServiceProviderDropdown, "Sub service provider dropdown");
		//	   wt.click(GeneralPractionerUnderSelectSubServiceProvider, "Generaral practionar checkbox");
		String Name=  wt.getRandomText(5);
		wt.sendValue(FirstName, Name, "First name");
		wt.sendValue(LastName, "TEST", "Last name");
		wt.sendValue(BusinessName, Name, "Business name");
		wt.sendValue(WebSiteLink, "Ac.com", "WebSite Link");
		wt.sendValue(NoteToAgent, "Nothing for agent to say", "Note to agent text box");
		wt.openAccordion(ContactAndAddressAccordian, "Address contact accordian");
		wt.holdOn(Duration.ofSeconds(3));
		wt.sendValue(AddressLine, "Jaunpur Bus Stand, Husainabad", "Address line");
		wt.sendValue(city, "Jaunpur", "City");
		wt.sendValue(State, "Uttar Pradesh", "State");
		wt.sendValue(Zipcode, "222002", "Postal code");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(contactTypeDropdown, "Contact type dropdown");
		wt.holdOn(Duration.ofSeconds(2));
		wt.click(primaryContactOptions, "primary contact option");
		wt.sendValue(phoneNumber, "9823456787", "Phone number");
		wt.sendValue(email, Name+"@yopmail.com", "Email");
		wt.click(SaveAndProceedToHomeButton, "Save and proceed to button");
		wt.holdOn(Duration.ofSeconds(10));
	//	String ActualProfessionalName=Name.toUpperCase();
	    wt.clearTextBox(SearchBar);
	    wt.sendValueWithEnter(SearchBar, Name, "Search bar");
	    wt.holdOn(Duration.ofSeconds(3));
	    wt.verifyInnerText(NoDataFoundText, "No Data Found", "No data found text");
	   wt.click(primaryMemberToggleButton, "primary member toggle button");
		String  ClientRevisedProfessionalCount= wt.getInnerText(ProfessionalCount);
		wt.holdOn(Duration.ofSeconds(3));
		wt.printDataInReport("Client initial professional count-" + primaryMemberInitialProfessionalCount + "Client revised professional count-" + ClientRevisedProfessionalCount);
	//	wt.printDataInReport("Spouse initial professional count-" + SpouseInitialProfessionalCount + "Spouse revised professional count-" + spouseRevisedProfessionalCount);
		wt.clearTextBox(SearchBar);
		wt.sendValueWithEnter(SearchBar, Name, "Search bar");
		String ActualSpeciality="Other's other";
		wt.verifyInnerText(ExpectedSpeciality,ActualSpeciality , "Specialty");	
   }
	
}
